### PR TITLE
Bind on Unix sockets

### PR DESCRIPTION
**Pull request by int-index**

### CODE REVIEW

**Comment by balsoft** [comment]
Doesn't work yet.

**Comment by balsoft** [comment]
`./result/hackage-search --unix /tmp/hackage.sock --hackage /tmp --frontend "$(readlink -f result)"`

And then

```
$ curl --unix-socket /tmp/hackage.sock -v http:/hackage-search/  
*   Trying /tmp/hackage.sock:0...
* Connected to hackage-search (/tmp/hackage.sock) port 80 (#0)
> GET / HTTP/1.1
> Host: hackage-search
> User-Agent: curl/7.70.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Transfer-Encoding: chunked
< Date: Fri, 17 Jul 2020 17:42:39 GMT
< Server: Warp/3.3.9
< 
* Connection #0 to host hackage-search left intact
```

**Comment by balsoft** [comment]
Ok, so it does work and apparently I don't know how to unix socket.

**Comment by balsoft** [comment]
```
$ curl --unix-socket /tmp/hackage.sock http:/hackage-search/hackage-search    
<html><head><title>root folder</title><style>table { margin: 0 auto; width: 760px; border-collapse: collapse; font-family: 'sans-serif'; }
table, th, td { border: 1px solid #353948; }
td.size { text-align: right; font-size: 0.7em; width: 50px }
td.date { text-align: right; font-size: 0.7em; width: 130px }
td { padding-right: 1em; padding-left: 1em; }
th.first { background-color: white; width: 24px }
td.first { padding-right: 0; padding-left: 0; text-align: center }
tr { background-color: white; }
tr.alt { background-color: #A3B5BA}
th { background-color: #3C4569; color: white; font-size: 1.125em; }
h1 { width: 760px; margin: 1em auto; font-size: 1em; font-family: sans-serif }
img { width: 20px }
a { text-decoration: none }
</style></head><body><h1>root</h1><table><thead><th class="first"><img src=".hidden/haskell.png"></th><th>Name</th><th>Modified</th><th>Size</th></thead><tbody><tr><td class="first"><img src=".hidden/folder.png" alt="Folder"></td><td><a href="bin">bin</a></td><td class="date"></td><td class="size"></td></tr></tbody></table></body></html>                                                                                                                                
```

Hmm, that doesn't appear to be it.

**Comment by balsoft** [comment]
Ok, made it work.

**Comment by int-index** [comment]
Yeah,  I tested these queries on my machine and they work:

* `curl --unix-socket hackage-search.sock http:/hackage-search/hackage-search/`
* `curl --unix-socket hackage-search.sock http:/hackage-search/hackage-search/rg/hello`

**Pull request merged**
